import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import BaseComponent from "@/components/BaseComponent";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#ddd8ff] flex items-center justify-center w-full h-screen">
        <Providers>
          <BaseComponent>
            {children}
          </BaseComponent>
        </Providers>
      </body>
    </html>
  );
}
